add flake lock
Running nix build outputs the following
```
[nix-shell:~/tmp/hello-x]$ nix build
warning: creating lock file '/home/waalge/tmp/hello-x/flake.lock'
warning: Git tree '/home/waalge/tmp/hello-x' is dirty
trace: Cargo.lock not found for project at path .
Please ensure the lockfile exists for your project.
If you are using a VCS, ensure the lockfile is added to the VCS and not
ignored (eg. run `git add /Cargo.lock` for git).

This project will be skipped and won't have any outputs generated.
Run `nix run .#generate-lockfiles` to generate lockfiles for projects
that don't have one.

error: flake 'git+file:///home/waalge/tmp/hello-x' does not provide
attribute 'packages.x86_64-linux.default' or
'defaultPackage.x86_64-linux'
```

Following the suggestion
```
[nix-shell:~/tmp/hello-x]$ nix run .#generate-lockfiles
trace: Cargo.lock not found for project at path .
Please ensure the lockfile exists for your project.
If you are using a VCS, ensure the lockfile is added to the VCS and not
ignored (eg. run `git add /Cargo.lock` for git).

This project will be skipped and won't have any outputs generated.
Run `nix run .#generate-lockfiles` to generate lockfiles for projects
that don't have one.

error: manifest path `/Cargo.toml` does not exist
fatal: /Cargo.lock: '/Cargo.lock' is outside repository at
'/home/waalge/tmp/hello-x'
```